server:
  context-path: /seller
  port: 8082
rpc.manager.url: http://localhost:8081/manager/
logging:
  level:
    com.googlecode.jsonrpc4j: debug

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.luo.api
spring:
  cache:
    type: hazelcast
