spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/bf?serverTimezone=UTC&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # timestamp 的时间格式化
  activemq:
    broker-url: tcp://10.5.16.14:61616
  jms:
    pub-sub-domain: true
server:
  context-path: /manager
  port: 8081
swagger:
  groupName: manager
